### ISSUE TITLE
[请教]

### ISSUE THREAD

**Issue by wuchangfeng** [lleobox/PYtypecho#2]
你好，挺喜欢你这个博客风格的，有几点问题想请教一下:
- 网站采用的 Mangodb 数据库，相对于传统的关系型数据库有什么好处吗？不太了解 非关系型数据库。。。
- 网站是部署在某个云平台吗？
- 网站的样式都是您自己写的吗？有没有用到一些第三方的库？
- Markdown 的支持是 是 flask 自带的库吗？

谢谢，还望有时间赐教一下。(:

**Comment by lleohao** [comment]
- 我采用 `Mongodb` 的原因主要一是因为自己测试的时候，这个比`Mysql`占用的资源低。第二点就是这个数据库比较灵活，跟我学的`python`、`javascript`比较贴合
- 网站部署在腾讯云上面，有学生优惠的话，每个月只需要1元
- 管理界面是自己写的，前台是套用了别人的主题（在底部可以看到我使用的主题，需要的话我也可以把静态的资源给你），自己修改了点
- Markdown 这个`Flask`支持的也有，不过我用的是 [editor.md](https://pandao.github.io/editor.md/)

**Comment by wuchangfeng** [comment]
@lleobox 好，我先学着，等弄熟悉了后，再找你要静态资源，谢谢啦。非常喜欢
