### ISSUE TITLE
[请教]

### ISSUE THREAD

**Issue by wuchangfeng** [lleobox/PYtypecho#3]
你好。由于对前端不是太熟悉。还是有点问题想要请教您：
-  看 UI 包底下还有 old_theme 这个有作用吗？还是弃用的？
-  editor.md 能够实时预览，非常好用。但是好像 不能支持 阅读更多那个功能，也就是普通的  ,不知道是不是我没有发现，还是就是没有。

谢谢。另外我最近也在自己的 Demo 中用上了 MongoDB 非常不错，感觉在没有复杂的逻辑关系情况下，用这个很顺手。

**Comment by lleohao** [comment]
old_theme 文件下面的是以前的模板，感觉不顺手就没用了
至于阅读更多的那个功能是前端的功能，不是 editor.md 的问题
这个功能我近段时间加上

MongoDB 确实很爽！！！

**Comment by lleohao** [comment]
一直谋划个重构这个程序，下个月开始
如果发现什么问题可以给我反馈下，谢谢啦
